version: 2

jobs:
  circleci-job:
    docker:
      - image: circleci/golang:1.15
    working_directory: ~/repo
    environment:
      DESTIP: 10.164.204.81
    steps:
      - checkout
      - run:
          name: apt update
          command: |
            sudo apt-get update
            sudo apt-get install -qq -y rsync
      - add_ssh_keys: 
          fingerprints:
          - "ee:bb:31:b1:91:29:dc:54:85:47:86:c6:1e:1b:24:d1"
      - run: 
          name: ssh-keyscan setting
          command: |
            ssh-keyscan -p 22 ${DESTIP} >> ~/.ssh/known_hosts
      - run: 
          name: rsync
          command: |
            rsync -auz ./index.html ec2-user@${DESTIP}:/home/ec2-user/
      - run:
          name: nginx install
          command: |
            ssh -p 22 ec2-user@${DESTIP} 'sudo amazon-linux-extras install nginx1 && sudo systemctl start nginx'
      - run:
          name: index.html setting
          command: |
            ssh ec2-user@${DESTIP} 'sudo mv index.html /usr/share/nginx/html/'


workflows:
  version: 2
  run-nginx:
    jobs:
      - circleci-job
